"use client";

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, MeshTransmissionMaterial } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { GLTF } from 'three-stdlib'
import { ThreeElements, useFrame } from '@react-three/fiber'
import './shaders/CityShaderMaterial' // Register the custom shader material
import './shaders/CityGroundShaderMaterial' // Register the custom ground shader material
import './shaders/CloudShaderMaterial' // Register the custom cloud shader material

type GLTFResult = GLTF & {
    nodes: {
        [name: string]: THREE.Mesh
    }
    materials: {
        [name: string]: THREE.Material
    }
}

export function SceneModel(props: ThreeElements['group']) {
    const { nodes, materials } = useGLTF('/models/scene.glb') as unknown as GLTFResult

    // Animation refs for shaders
    const cloudMat = useRef<any>(null);
    const groundMat = useRef<any>(null);

    React.useEffect(() => {
        // useFrame is not available inside the component body directly usually if not careful? 
        // No, it's fine.
    }, [])

    useFrame((state, delta) => {
        if (cloudMat.current) {
            cloudMat.current.uTime = state.clock.elapsedTime;
        }
        if (groundMat.current) {
            // Updated ground shader also has uTime
            groundMat.current.uTime = state.clock.elapsedTime;
        }
    });

    return (
        <group {...props} dispose={null}>
            <group position={[0, -23.641, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.City_City_0.geometry}
                >
                    <cityShaderMaterial />
                </mesh>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.City_City_0001.geometry}
                >
                    <cityShaderMaterial />
                </mesh>
            </group>
            <group position={[8.047, 0.288, -2.653]}>
                <RigidBody type="fixed" colliders="trimesh">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.floor.geometry}
                        material={materials.carrelage_046_ovcolbfbfbfcolpic12contpic03_Room_Entity_Material}
                    />
                </RigidBody>
                <RigidBody type="fixed" colliders="trimesh">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.floor_sep.geometry}
                        material={materials.gris_001_Room_Entity_Material}
                    />
                </RigidBody>
                <RigidBody type="fixed" colliders="trimesh">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.grass_ground.geometry}
                        material={materials.gazon_007_Room_Entity_Material}
                    />
                </RigidBody>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.bois_080}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials.buisson___buisson_branche_texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.buisson___buisson_branche_texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.buisson___buisson_texture}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.carrelage_046_ovcolacacaccolpic12contpic02_Wall_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.carrelage_046_ovcolbfbfbfcolpic12contpic03_Wall_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials.cuir_007}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.cuisine_evier_001___mat_verni}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.armoire_002___mirror_miroir}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.cuisine_ilot_002___mat_verni}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.cuisine_meuble_bas_001___mat_microonde}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials.cuisine_meuble_bas_001___mat_pied}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.cuisine_meuble_bas_001___mat_poignet}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.cuisine_meuble_bas_001___mat_porte}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.cuisine_meuble_bas_001___mat_verni}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={
                        materials.cuisine_meuble_bas_003____cuisine_meuble_bas_003_cuisine_meuble_bas_003_cuisine_meuble_bas_003verni
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={
                        materials.cuisine_meuble_haut_001____cuisine_meuble_haut_001_cuisine_meuble_haut_001_cuisine_meuble_haut_001verni
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={
                        materials.cuisine_meuble_haut_002____cuisine_meuble_haut_002_cuisine_meuble_haut_002_cuisine_meuble_haut_002verni
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={
                        materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_00108___default
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={
                        materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001metal
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={
                        materials.cuisine_plaque_cuisson_001____cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001_cuisine_plaque_cuisson_001verni
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.cypres___mat_cypres_tronc}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials.douche_italienne_002____douche_italienne__verre}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials.douche_italienne_002____douche_italienne_fond}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials.douche_italienne_002____douche_italienne_trou_douche}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.douche_italienne_002____douche_italienne_trous_douche}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials.enduit_004_Room_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials.enduit_004_Wall_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.baie_vitree_002___verre}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials.fake_mat_0_0_0_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_41.geometry}
                    material={materials.fake_mat_107_107_107_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials.fake_mat_142_142_142_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_43.geometry}
                    material={materials.fake_mat_149_149_149_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_44.geometry}
                    material={materials.fake_mat_165_165_165_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_45.geometry}
                    material={materials.fake_mat_204_202_198_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={materials.fake_mat_229_229_229_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_47.geometry}
                    material={materials.fake_mat_248_249_253_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_48.geometry}
                    material={materials.fake_mat_254_254_254_255}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_49.geometry}
                    material={materials.fake_mat_255_255_255_32}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.baie_vitree_002___wood_dormant}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials.fauteuil_017___mat_tissus057_2sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_51.geometry}
                    material={materials.fenetre_002____fenetre_002fenetre_002_d1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={materials.fenetre_002____fenetre_002fenetre_002_p1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_53.geometry}
                    material={materials.fenetre_002____fenetre_verre}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials.fenetre_029______phong1sg6}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_56.geometry}
                    material={materials.gris_001}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_58.geometry}
                    material={materials.gris_001_Wall_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_59.geometry}
                    material={materials.horloge_002___bis_mat_horlogesg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.beige_006_Wall_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_60.geometry}
                    material={materials.hotte_003___mat_hote}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_61.geometry}
                    material={materials.lavabo_006___mat_blanc1sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_62.geometry}
                    material={materials.lavabo_006___mat_blanc2sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_63.geometry}
                    material={materials.lavabo_006___mat_blanc3sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_64.geometry}
                    material={materials.lavabo_006___mat_metalbasique001sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_65.geometry}
                    material={materials.lave_mains_001___lave_mains_001_blinn1sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_66.geometry}
                    material={materials.lave_mains_001___lave_mains_001_blinn4sg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.marbre_004_ovcol737373colpic12contpic11}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={materials['mirror.nocompress']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_69.geometry}
                    material={materials.mur_vegetal_off___phong150}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_70.geometry}
                    material={materials.mur_vegetal_off___phong151}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_71.geometry}
                    material={materials.mur_vegetal_off___phong31}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_72.geometry}
                    material={materials.pack_002_sdb_deroule_papier___01___defaulte}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_73.geometry}
                    material={materials.pack_003_salon_television___material__83}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_75.geometry}
                    material={materials.pack_005_salle_de_sport_velo_appartement___nopaint_ecran}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_76.geometry}
                    material={materials.plante_interieur_off___bis_palmier_tronc2}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_78.geometry}
                    material={materials.plante_vase_off_001___phong37}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_79.geometry}
                    material={materials.porte_010___verre}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.blanc_001}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_80.geometry}
                    material={materials.porte_serviette_005___metal}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_81.geometry}
                    material={materials.prise_01____prise_prise_prisematerial__126}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_82.geometry}
                    material={materials.prise___material__49}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_83.geometry}
                    material={
                        materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006glacon
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_84.geometry}
                    material={
                        materials.refrigerateur_006____refrigerateur_006_refrigerateur_006_refrigerateur_006porte
                    }
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_85.geometry}
                    material={materials.resine_tresse_blanche_ovcol737373colpic12contpic11}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_86.geometry}
                    material={materials.table_basse_016___mat_vitresg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_87.geometry}
                    material={materials.tex_terreau}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.tissus_030_ovcol868686colpic12contpic00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.blanc_001_Room_Entity_Material}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_90.geometry}
                    material={materials.tissus_044_ovcolacacaccolpic12contpic02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_91.geometry}
                    material={materials.tissus_065_ovcol868686colpic12contpic00}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_92.geometry}
                    material={materials.tissus_071_ovcolacacaccolpic12contpic02}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_93.geometry}
                    material={materials.vitrine_004___mat_vitresg}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_94.geometry}
                    material={materials.wc_005____base}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_95.geometry}
                    material={materials.wc_005____couvercle}
                />
                <RigidBody type="fixed" colliders="trimesh">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.outside_floor.geometry}
                        material={materials.bitume_001_ovcol737373colpic12contpic11_Room_Entity_Material}
                    />
                </RigidBody>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.pine_trees.geometry}
                    material={materials.cypres___mat_cypres_feuille}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.pool_water.geometry}
                    material={materials.texture_eau_piscine_ovcol5ca1d7colpic11contpic01}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tree_pots.geometry}
                    material={materials.plante_interieur_off___phong80}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.tree_pots_thin.geometry}
                    material={materials.pack_004_salon_001_plante___nopaint_feuilles}
                />
                <RigidBody type="fixed" colliders="trimesh">
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.walls.geometry}
                        material={materials.blanc_001_Wall_Entity_Material}
                    />
                </RigidBody>
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.building_bottom.geometry}
                material={nodes.building_bottom.material}
                position={[1.698, 1.043, -2.653]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.city_ground.geometry}
                position={[0, -23.641, 0]}
            >
                <cityGroundShaderMaterial
                    ref={groundMat}
                    transparent
                    uRadiusStart={200}
                    uRadiusEnd={500}
                    uColorWater={new THREE.Color("#4fa1d8")}
                    uColorGrass={new THREE.Color("#5e9e58")}
                    uColorPavement={new THREE.Color("#4a7d45")} // Darker Green
                    uColorEdge={new THREE.Color("#e8e8e8")}
                />
            </mesh>

            {/* Cloud Layer */}
            <mesh position={[0, -18, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <planeGeometry args={[800, 800]} />
                <cloudShaderMaterial
                    ref={cloudMat}
                    transparent
                    uColor={new THREE.Color("#ffffff")}
                    uCloudDensity={0.4}
                    uCloudSpeed={0.15}
                />
            </mesh>

            {/* Blur Layer */}
            {/* COMMENT: This layer blurs the city background. If the scene is too white or 
                you can't see the city, reduce 'roughness' (e.g. to 0.2) or remove this mesh. */}
            <mesh position={[0, -20, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <planeGeometry args={[800, 800]} />
                <MeshTransmissionMaterial
                    transmission={1}
                    roughness={0.55} // Reduce this to 0.1-0.2 for better visibility
                    thickness={5}
                    ior={1.0}
                    chromaticAberration={0.01}
                    anisotropy={0}
                    distortion={0}
                    distortionScale={0}
                    temporalDistortion={0}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('/models/scene.glb')
